//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Дипломный_проект_Зайцев
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Дипломный_проект_Зайцев_20_КИС_1Entities : DbContext
    {
        public Дипломный_проект_Зайцев_20_КИС_1Entities()
            : base("name=Дипломный_проект_Зайцев_20_КИС_1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Должность_сотрудника> Должность_сотрудника { get; set; }
        public virtual DbSet<Заказы> Заказы { get; set; }
        public virtual DbSet<Категория_товара> Категория_товара { get; set; }
        public virtual DbSet<Контрагенты> Контрагенты { get; set; }
        public virtual DbSet<Продажи> Продажи { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
        public virtual DbSet<Статус_заказа> Статус_заказа { get; set; }
        public virtual DbSet<Товары> Товары { get; set; }
    }
}
