//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Дипломный_проект_Зайцев
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        public int ид_заказа { get; set; }
        public int ид_контрагента { get; set; }
        public int ид_товара { get; set; }
        public int Количество { get; set; }
        public int ид_статуса { get; set; }
        public System.DateTime Дата_заказа { get; set; }
        public double Стоимость { get; set; }
    
        public virtual Контрагенты Контрагенты { get; set; }
        public virtual Статус_заказа Статус_заказа { get; set; }
        public virtual Товары Товары { get; set; }
    }
}
