//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Дипломный_проект_Зайцев
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продажи
    {
        public int ид_продажи { get; set; }
        public int ид_товара { get; set; }
        public int ид_контрагента { get; set; }
        public double Общая_стоимость { get; set; }
        public System.DateTime Дата_продажи { get; set; }
        public int Количество { get; set; }
    
        public virtual Контрагенты Контрагенты { get; set; }
        public virtual Товары Товары { get; set; }
    }
}
